# Generated by Django 4.0 on 2022-04-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=b'I01\n', serialize=False, to='auth.user')),
                ('test1', models.CharField(max_length=50)),
            ],
        ),
    ]
