# Generated by Django 4.0 on 2022-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test1',
            field=models.TextField(),
        ),
    ]
