# Generated by Django 4.0 on 2022-04-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_profile_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
