# Generated by Django 4.0 on 2022-04-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='at',
        ),
    ]
