# Generated by Django 4.0 on 2022-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='ver_code',
            field=models.TextField(),
        ),
    ]
